projekt_test:
    path:     /test
    defaults: { _controller: ProjektBundle:Default:test }

projekt_index:
    path:     /index
    defaults: { _controller: ProjektBundle:Projekt:index }

projekt_new:
    path:     /new
    defaults: { _controller: ProjektBundle:Projekt:new }

projekt_show:
    path:     /{id}/show
    defaults: { _controller: "ProjektBundle:Projekt:show" }
    methods:  GET

main_new:
    path:     /{projektId}/main/new
    defaults: { _controller: ProjektBundle:Main:new }

submain_new:
    path:     /submain/new
    defaults: { _controller: ProjektBundle:Submain:new }
